---
minimum_pre_commit_version: 3.7.0

repos:

# commit-msg hooks
# ----------

# Conventional Commit message checker (commitizen)
- repo: https://github.com/commitizen-tools/commitizen
  rev: v3.21.3
  hooks:
  - id: commitizen
    stages:
    - commit-msg

# pre-commit hooks
# ----------

# Standard pre-commit rules
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v6.0.0
  hooks:
  - id: check-case-conflict
  - id: check-docstring-first
  - id: check-executables-have-shebangs
  - id: check-shebang-scripts-are-executable
  - id: check-toml
  - id: detect-private-key
  - id: end-of-file-fixer
  - id: requirements-txt-fixer
  - id: trailing-whitespace
    args:
    - --markdown-linebreak-ext=md
